//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tble_login
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public int ID { get; set; }
    }
}
